### PR TITLE
home page revamp 2023

### PR DESCRIPTION
**Pull request by System-x64**
@vaxerski  Finally its done... 
- Added additional meta information that ain't visible to the user but is silently used by google's ranking system to show this site properly in google search 
- Added newer rices since its been a while since we've been seeing those old rices on the home page 
- All of the 3 videos have been re-done, this time in 60fps to really show the smoothness 
- Videos from now will only load when brought into viewport, this significantly reduces the loading time when the site is initially loaded 
- I've removed the link to "Wall of Fame" page for now since they were from december 2022, although the screenshots are still there in the community rices section on the home page. I decided not to delete any code though as we can bring the page back when another competition is being held with newer rices
- re styled footer in mobile view 
- fixed alignment flaws (both desktop and mobile)
- fixed "fat favicon" issue in previous versions of the site
- removed "and more" and "install hyprland" from the bottom as it didn't loook clean and also looked repetitive
- removed junk files (there are alot of junk css code aswell that i'll remove later)  
- the top section now will take the full available height making sure the "features" part ain't shown before scrolling
- some more minor changes 

PS. to anyone editing the links in the navbar/header, don't forget to also update it for the mobile view...the code for that is at the bottom at `<div class="overlay__content">` otherwise the links wont appear in the hamburger menu 

also thx @azymandias-el for the updated 404 page...i was too lazy to revamp that :P

### CODE REVIEW

**Comment by vaxerski** [comment]
do not remove the wall of fame link, it was a promise I will keep to post all the podium rices there. It will be updated with new competitions.

**Comment by System-x64** [comment]
@vaxerski Done

**Comment by System-x64** [comment]
oh wait i fked up something don't accept this pr yet

**Comment by System-x64** [comment]
yeah now you can

**Comment by System-x64** [comment]
Uhh..can we merge it now? @vaxerski

**Comment by vaxerski** [comment]
yeah bro sorry for not being a robot and having shit to do irl. I'll test this today evening probably and merge if its all good. 

let me also remind you this repo is not synced with the website, I have to update it manually

**Comment by System-x64** [comment]
> yeah bro sorry for not being a robot and having shit to do irl.

Chill bro...I know u have other things to worry about, I was just confirming u saw those newer commit, take your own time to test and deploy them, I have no complaints. Sry for being this annoying, I am the way I am 😓

**Comment by vaxerski** [comment]
image

spacing too big - cringe

image

frozen

image

frozen

Also you've reverted the buttons #12 added

**Comment by vaxerski** [comment]
disregard my frozen comments perhaps... idk switched from it and back to it and it now plays...?

**Comment by System-x64** [comment]
> Spacing too big

The spacing takes the full available height of the viewport, zoom the site and reload and you'll see the spacing shrinks

> frozen

Is your monitor this huge that all the videos are coming in viewport before the site loads? In that case it'll remain paused as it should, the script only runs when you _come_ into viewport and not from the start, This is the reason going back and coming fixed this issue, again zooming in and then scrolling to the video will fix the issue.

> #12

Indeed, I fetched this repo before that commit and edited those lines so they got overwritten, ill change them back in a later commit

Also, if you are not happy with the viewport height idea, remove line 256-359 in home.ejs and set `height: 100px(or whatever you like);` for `#top` in home.css

**Comment by System-x64** [comment]
Fk right, idk how that extra height came there, really sorry 
> spacing too big - cringe

**Comment by vaxerski** [comment]
LGTM, thank you!

**Comment by System-x64** [comment]
uhh,..why is https://hyprland.org and https://www.hyprland.org showing different imgs(in slider) and videos (vid 2 and 3)? Did you delete the old code before adding this newer old?

**Comment by vaxerski** [comment]
ctrl+shift+r to clear cache and reload...

**Comment by System-x64** [comment]
Ah yes!

**Pull request merged**
