### PR TITLE
updated Copyright Year, wall of fame page

### PR DESCRIPTION
**Pull request by System-x64**

### CODE REVIEW

**Comment by System-x64** [comment]
Belated Chirstmas and Happy new year guys, sowwy i was lost with my exams, finally i can work on this site again

I am planning to update the rices and demo videos with a more higher quality ones and also make the home site just a bit more informative

Anyways looking forward for a wonderful year ahead, Cheers!

**Comment by vaxerski** [comment]
ping me after the 22nd

**Comment by System-x64** [comment]
Sure

**Comment by System-x64** [comment]
@vaxerski

**Pull request merged**
