### PR TITLE
Add padding-bottom to button #install-hypr

### PR DESCRIPTION
**Pull request by sherichev**
Before:
image
After:
image

### CODE REVIEW

**Comment by vaxerski** [comment]
remind me in 7 days please

**Comment by System-x64** [comment]
weird it doesn't happen for me..i'll add a bottom padding anyways, thanks!
screenshot_20230119_194333

**Comment by sherichev** [comment]
> weird it doesn't happen for me..i'll add a bottom padding anyways, thanks! screenshot_20230119_194333

Maybe this thing appears only in Chromium based browsers, didnt check it..

**Comment by System-x64** [comment]
> Maybe this thing appears only in Chromium based browsers, didnt check it..

checked on brave still not able to reproduce this issue :(
may I know which OS are you viewing the site with, and at what resolution?
screenshot_20230119_222441

**Comment by sherichev** [comment]
> > Maybe this thing appears only in Chromium based browsers, didnt check it..
> 
> checked on brave still not able to reproduce this issue :( may I know which OS are you viewing the site with, and at what resolution? And the browser screenshot_20230119_222441

Currently on Win10(res: FullHD) and issue still persists in Chrome and Edge..

**Comment by System-x64** [comment]
Crap right! On windows its on every browser possible, can't believe I never visited this site on windows, tysm @sherichev

**Comment by System-x64** [comment]
Now i'd have to check if each element is displaying properly on each os properly or not :(

**Comment by sherichev** [comment]
> remind me in 7 days please

Can i remind you about my PR?

**Comment by System-x64** [comment]
@vaxerski

**Pull request merged**
