### PR TITLE
optimize images

### PR DESCRIPTION
**Pull request by NotAShelf**
Ran `optipng` on existing pngs to help with the repo size. Achieves an average of 25% decrease in image sizes without compromising on image quality.

### CODE REVIEW

**Comment by Visual-Dawg** [comment]
I would make more sense to convert the images to `webp` instead

**Comment by NotAShelf** [comment]
I don't think there's a problem in keeping pngs. IIRC webp comes with its own set of downsides (e.g. security vulnerabilities)

**Comment by Visual-Dawg** [comment]
Webp is the standard for images on the web and recommended by Google too. There are also newer formats, but they are not widely supported.
What security vulnerabilities exist though?

**Comment by NotAShelf** [comment]
I may be hallucinating. Eitherway, I trust your judgement more than my own on this. Should I handle conversion and force push?

**Comment by vaxerski** [comment]
webp is famous for security vulnerabilities indeed, I'd rather stick with png

**Comment by Visual-Dawg** [comment]
Lets simply not allow maliciously crafted webp's into our codebase
Converting one from png is probably fine (and its so much smaller than png)

Mar 6, 2024, 20:16 by ***@***.***:

**Pull request closed without merging**
