### PR TITLE
Some styling changes (buttons, hover effects, and centered wall of fame rices)

### PR DESCRIPTION
**Pull request by azymandias-el**
Buttons done only for the home.css (home.ejs and rices.ejs improved, only 404.ejs untouched)
The hover changes were added because on using the transform: scale() function the text gets blurred while increasing size so I thought adding a more visible change would take attention away from that.

Border radius:
rad1

On hovering the buttons:
hover1

Centered the rice images on the Wall of Fame page and cleaned up classes: [Also made some of that `el aequo` stuff more understandable ...]
wof

New 404 page + icon (the new 404 page has the same styling/nav as the other pages)

### CODE REVIEW

**Comment by azymandias-el** [comment]
Also, can we change the 404 page styling? There are some things I'd like to change, such as the Hyprland logo scale() animation (text blurs, looks bad) and the button's hover appearance.

**Comment by vaxerski** [comment]
> can we change the 404 page styling

you can change anything as long as it looks good, I don't care tbh lol

**Comment by azymandias-el** [comment]
> you can change anything as long as it looks good

Alright, then I'll finish that and ready the draft for review.

**Comment by azymandias-el** [comment]
@vaxerski Done ... please have a look.

**Comment by azymandias-el** [comment]
@vaxerski could you please review this PR

**Comment by vaxerski** [comment]
ye

**Review by vaxerski — APPROVED** [review]
idk looks like some funny text, seems good

**Pull request merged**
