### PR TITLE
Fix for last PR

### PR DESCRIPTION
**Pull request by EpicGamer007**
Sorry 'bout the other pr breaking for whatever reason.

From the last pr I made, I simply reverted to using commonjs (`require("package")`) rather than ES6 imports(`import package from "package"`). This should fix up the problem that was present in the last pr :)

### CODE REVIEW

**Comment by vaxerski** [comment]
image

just me?

**Comment by EpicGamer007** [comment]
? probably. I haven't touched the site itself except for the navbar and cursor. site looks fine to me rn
image

**Comment by EpicGamer007** [comment]
if its a problem with sliderjs not loading, that is a different story and probably would be a CSP issue, but i explicitly made it so that sliderjs and jquery can be loaded in through the csp. if its problematic for some browsers (which it shouldn't be, because [all modern browsers support CSP](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP#browser_compatibility)), we can either a) make the content security policy open (so it can load resources from anywhere) and disregard security or b) copy the sliderjs files into the project itself. If it isn't a CSP issue, its an issue with sliderjs itself which I would have no idea what to do.

I would appreciate if you can send your browser console log and network tab for the main file (see two images)
image
image

**Comment by vaxerski** [comment]
20230223_21h31m47s_grim
20230223_21h31m40s_grim

**Comment by EpicGamer007** [comment]
that is so weird. i wonder why this didn't happen to me 😕. This is an easy fix however. simply, swiperjs uses a custom font with the `data:` tag which was not in the CSP. Changing the font-src to `font-src 'self' data:;` will fix it. I will submit one last pr and everything should work fine.

**Pull request merged**
