### PR TITLE
Add sheepmilk avatar

### PR DESCRIPTION
**Pull request by morr0ne**
Add myself to the profiles

### CODE REVIEW

**Comment by vaxerski** [comment]
it's autogenerated, no

**Comment by Visual-Dawg** [comment]
Hey, PRing a profile picture is fine. 
Ill update the generation then accordingly

However, your Discord level is not high enough to be featured (maybe I found the wrong account, in this case just tell me your user name :D )

**Comment by morr0ne** [comment]
> However, your Discord level is not high enough to be featured (maybe I found the wrong account, in this case just tell me your user name :D )

The user is @milksheep, I'd assume I'm an high enough level?

**Comment by Visual-Dawg** [comment]
Not yet, sorry

**Pull request closed without merging**
