### PR TITLE
Some improvements

### PR DESCRIPTION
**Pull request by vdawg-git**

### CODE REVIEW

**Comment by vaxerski** [comment]
wat

**Comment by vdawg-git** [comment]
Mostly clean-up/refactoring and a tiny amount of making it look better

**Review by vaxerski — APPROVED** [review]
mhm

**Comment by vdawg-git** [comment]
I'm not going to sneak cute anime girls in there xDDD
(It's not your birthday anymore :P )

**Comment by vaxerski** [comment]
wont build

**Comment by vaxerski** [comment]
```
Error: ENOENT: no such file or directory, open '/run/media/vaxry/Uber SSD 1/PROJECTS/hyprland-website/.svelte-kit/output/server/entries/content/plugins.toml'
```

**Comment by vdawg-git** [comment]
Ah, I'll fix that. You don't really need to deploy that anyway. It's doesn't change much in the website

1 Sept 2024, 16:23 by ***@***.***:

**Pull request merged**
